"use client";

import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ImagePlus } from "lucide-react";

export function EventForm() {
  const router=useRouter(); const fileRef=useRef<HTMLInputElement>(null); const formRef=useRef<HTMLFormElement>(null); const [image,setImage]=useState(""); const [message,setMessage]=useState("");
  const save=(publish:boolean)=>{const element=formRef.current;if(!element)return;const form=new FormData(element);const name=String(form.get("name")||"").trim();if(!name){setMessage("행사명을 입력해주세요.");return}const slug=name.toLowerCase().replace(/[^a-z0-9가-힣]+/g,"-").replace(/^-|-$/g,"");const item={id:crypto.randomUUID(),name,description:form.get("description"),startsAt:form.get("startsAt"),endsAt:form.get("endsAt"),venue:form.get("venue"),visibility:form.get("visibility"),brandColor:form.get("brandColor"),coverImage:image,slug,status:publish?"게시":"임시 저장",applicants:0,checkins:0,createdAt:new Date().toISOString()};const events=JSON.parse(localStorage.getItem("noogu:admin-events")||"[]");localStorage.setItem("noogu:admin-events",JSON.stringify([item,...events]));if(publish)router.push(`/event/${slug}`);else{setMessage("임시 저장했습니다.");setTimeout(()=>router.push("/admin/events"),700)}};
  return <form ref={formRef} onSubmit={event=>{event.preventDefault();save(true)}}><div className="desktop-grid section"><section className="card card-pad form-grid"><h2 className="section-title">기본 정보</h2><label className="field"><span>행사명 *</span><input name="name" className="input" required placeholder="예: Fashion Networking Day"/></label><label className="field"><span>행사 설명</span><textarea name="description" className="textarea" placeholder="참가자가 행사를 이해할 수 있도록 소개해주세요."/></label><div className="two-col"><label className="field"><span>시작 일시</span><input name="startsAt" className="input" type="datetime-local"/></label><label className="field"><span>종료 일시</span><input name="endsAt" className="input" type="datetime-local"/></label></div><label className="field"><span>장소</span><input name="venue" className="input" placeholder="장소명 또는 주소"/></label><div className="two-col"><label className="field"><span>공개 방식</span><select name="visibility" className="select"><option>공개</option><option>비공개</option><option>승인제</option></select></label><label className="field"><span>브랜드 컬러</span><input name="brandColor" className="input" type="color" defaultValue="#bbf34a"/></label></div></section><aside><input ref={fileRef} hidden type="file" accept="image/*" onChange={event=>{const file=event.target.files?.[0];if(file)setImage(URL.createObjectURL(file))}}/><button type="button" className="card event-image-upload" style={image?{backgroundImage:`url(${image})`}:{}} onClick={()=>fileRef.current?.click()}><div><div className="empty-icon"><ImagePlus size={22}/></div><b>행사 커버 이미지</b><p className="list-sub">권장 1600 × 900px</p></div></button><section className="card card-pad section"><h2 className="section-title">랜딩페이지 구성</h2><p className="page-copy">Hero · 행사 소개 · 프로그램 · 일시 · 장소 · FAQ · 문의하기</p><div className="divider"/><p className="list-sub">생성 후 블록별로 순서와 내용을 편집할 수 있습니다.</p></section>{message&&<p className="form-message">{message}</p>}<div className="two-col section"><button type="button" className="button light" onClick={()=>save(false)}>임시 저장</button><button className="button full" type="submit">행사 생성 및 랜딩페이지 열기</button></div></aside></div></form>;
}
