"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Check, Copy } from "lucide-react";

type Profile={name:string;company:string;jobTitle:string;phone:string;email:string;website:string;headline:string;bio:string;handle:string};
const fallback:Profile={name:"김한재",company:"NOOGU",jobTitle:"Product Lead",phone:"010-2408-2027",email:"hanjae@noogu.kr",website:"https://noogu.kr",headline:"사람과 사람 사이의 좋은 맥락을 만듭니다.",bio:"사람과 사람 사이의 좋은 맥락이 오래 남는 제품을 만듭니다.",handle:"hanjae"};

export function ProfileEditor(){const router=useRouter();const [form,setForm]=useState(fallback);const [copied,setCopied]=useState(false);useEffect(()=>{const saved=localStorage.getItem("noogu:profile");if(saved)setForm(current=>({...current,...JSON.parse(saved)}))},[]);const change=(key:keyof Profile,value:string)=>setForm(current=>({...current,[key]:value}));const save=()=>{localStorage.setItem("noogu:profile",JSON.stringify({...form,updatedAt:new Date().toISOString()}));router.push("/profile")};const copy=async()=>{await navigator.clipboard?.writeText(`${location.origin}/u/${form.handle}`);setCopied(true);setTimeout(()=>setCopied(false),1500)};return <div className="form-grid"><section className="card card-pad form-grid"><div className="two-col"><label className="field"><span>이름 *</span><input className="input" value={form.name} onChange={event=>change("name",event.target.value)}/></label><label className="field"><span>프로필 주소</span><div className="input-action"><input className="input" value={form.handle} onChange={event=>change("handle",event.target.value.toLowerCase().replace(/[^a-z0-9_-]/g,""))}/><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>}</button></div></label></div><div className="two-col"><label className="field"><span>회사</span><input className="input" value={form.company} onChange={event=>change("company",event.target.value)}/></label><label className="field"><span>직급</span><input className="input" value={form.jobTitle} onChange={event=>change("jobTitle",event.target.value)}/></label></div><label className="field"><span>한줄 소개</span><input className="input" value={form.headline} onChange={event=>change("headline",event.target.value)} maxLength={120}/></label><label className="field"><span>소개글</span><textarea className="textarea" value={form.bio} onChange={event=>change("bio",event.target.value)} maxLength={2000}/></label></section><section className="card card-pad form-grid"><h2 className="section-title">연락처</h2><div className="two-col"><label className="field"><span>이메일</span><input className="input" type="email" value={form.email} onChange={event=>change("email",event.target.value)}/></label><label className="field"><span>전화번호</span><input className="input" value={form.phone} onChange={event=>change("phone",event.target.value)}/></label></div><label className="field"><span>웹사이트</span><input className="input" value={form.website} onChange={event=>change("website",event.target.value)}/></label></section><button className="button green full" onClick={save} disabled={!form.name.trim()||!form.handle.trim()}>변경사항 저장</button></div>}
