"use client";
import { useEffect, useMemo, useState } from "react";
import { Check, Search, X } from "lucide-react";
import { participants as source } from "@/lib/mock-data";

export function ParticipantTable() {
  const [participants,setParticipants]=useState(source); const [selected,setSelected]=useState<string[]>([]); const [query,setQuery]=useState(""); const [toast,setToast]=useState("");
  useEffect(()=>{const saved=localStorage.getItem("noogu:participant-statuses");if(saved){const statuses=JSON.parse(saved);setParticipants(items=>items.map(item=>({...item,status:statuses[item.name]||item.status}))) }},[]);
  const filtered=useMemo(()=>participants.filter(p=>`${p.name} ${p.company} ${p.role}`.toLowerCase().includes(query.toLowerCase())),[participants,query]);
  const update=(status:string,names=selected)=>{const next=participants.map(p=>names.includes(p.name)?{...p,status}:p);setParticipants(next);localStorage.setItem("noogu:participant-statuses",JSON.stringify(Object.fromEntries(next.map(p=>[p.name,p.status]))));setSelected([]);setToast(`${names.length}명을 ${status} 처리했습니다.`);setTimeout(()=>setToast(""),1600)};
  return <><div className="action-row" style={{marginBottom:14}}><div className="search" style={{flex:1}}><Search size={17}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="이름, 회사, 이메일 검색"/></div>{selected.length>0&&<><button className="button green" onClick={()=>update("승인")}><Check size={16}/> {selected.length}명 승인</button><button className="button danger" onClick={()=>update("반려")}><X size={16}/> 반려</button></>}</div><div className="card table-card table-wrap"><table className="table"><thead><tr><th><input type="checkbox" checked={selected.length===filtered.length&&filtered.length>0} onChange={e=>setSelected(e.target.checked?filtered.map(p=>p.name):[])}/></th><th>참가자</th><th>회사 / 직급</th><th>신청일</th><th>상태</th><th>처리</th></tr></thead><tbody>{filtered.map(p=><tr key={p.name}><td><input type="checkbox" checked={selected.includes(p.name)} onChange={()=>setSelected(s=>s.includes(p.name)?s.filter(n=>n!==p.name):[...s,p.name])}/></td><td><b>{p.name}</b></td><td>{p.company} · {p.role}</td><td>{p.applied}</td><td><span className={`status ${p.status==="승인"||p.status==="체크인"?"approved":p.status==="반려"?"rejected":"pending"}`}>{p.status}</span></td><td><div className="action-row"><button className="chip green" style={{border:0}} onClick={()=>update("승인",[p.name])}>승인</button><button className="chip" style={{border:0}} onClick={()=>update("반려",[p.name])}>반려</button></div></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty"><h3>검색 결과가 없습니다</h3></div>}</div>{toast&&<div className="toast">{toast}</div>}</>;
}
