import { Activity, CheckCircle2, Download, UserCheck, UsersRound } from "lucide-react";
import { AdminShell } from "@/components/admin-shell";

const hourly=[22,38,64,88,72,46,30];
const eventRows=[
  ["Fashion Networking Day","98","426","4.3","69%"],
  ["Material Futures 2027","112","518","4.6","88%"],
  ["Seoul Startup Meetup","76","284","3.7","81%"],
];

export default function ReportsPage(){return <AdminShell active="리포트"><header className="admin-top"><div><span className="eyebrow">Networking analytics</span><h1 className="page-title" style={{fontSize:34}}>네트워킹 리포트</h1><p className="page-copy">참가부터 체크인, 실제 연결까지 행사의 전환을 확인하세요.</p></div><a href="/api/exports/connections.xlsx" className="button green"><Download size={17}/> XLSX 다운로드</a></header><section className="metric-grid"><div className="card metric"><span className="metric-icon"><UserCheck size={18}/></span><div className="metric-value">98</div><div className="metric-label">체크인 참가자</div></div><div className="card metric"><span className="metric-icon"><UsersRound size={18}/></span><div className="metric-value">426</div><div className="metric-label">생성된 연결</div></div><div className="card metric"><span className="metric-icon"><Activity size={18}/></span><div className="metric-value">4.3</div><div className="metric-label">1인 평균 연결</div></div><div className="card metric"><span className="metric-icon"><CheckCircle2 size={18}/></span><div className="metric-value">63%</div><div className="metric-label">메모 작성률</div></div></section><section className="report-grid section"><div className="card card-pad"><div className="section-head"><div><h2 className="section-title">시간대별 연결</h2><p className="list-sub">Fashion Networking Day</p></div><span className="chip green">총 426건</span></div><div className="chart-bars">{hourly.map((value,index)=><div className="chart-column" key={value+index}><div className="chart-bar" style={{height:`${value}%`}}/><span className="chart-label">{14+index}시</span></div>)}</div></div><div className="card card-pad"><div className="section-head"><h2 className="section-title">참가 전환</h2><span className="chip">Funnel</span></div>{[["신청","186",100],["승인","142",76],["체크인","98",53],["1회 이상 연결","82",44]].map(([label,value,width])=><div key={String(label)} style={{marginTop:20}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:8}}><b>{label}</b><span>{value}명</span></div><div className="progress-track"><div className="progress-bar" style={{width:`${width}%`}}/></div></div>)}</div></section><section className="section"><div className="section-head"><h2 className="section-title">행사별 성과</h2><span className="section-link">최근 3개 행사</span></div><div className="card table-card table-wrap"><table className="table"><thead><tr><th>행사</th><th>체크인</th><th>연결</th><th>1인 평균</th><th>체크인율</th></tr></thead><tbody>{eventRows.map(row=><tr key={row[0]}>{row.map((cell,index)=><td key={cell}>{index===0?<b>{cell}</b>:cell}</td>)}</tr>)}</tbody></table></div></section></AdminShell>}
