"use client";

import { useRef, useState } from "react";
import { CheckCircle2, Upload } from "lucide-react";

export function RegisterForm({ eventSlug = "fashion-networking-2027" }: { eventSlug?: string }) {
  const [sent,setSent]=useState(false); const [cardName,setCardName]=useState(""); const [applicant,setApplicant]=useState(""); const fileRef=useRef<HTMLInputElement>(null);
  const submit=(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries());const applications=JSON.parse(localStorage.getItem("noogu:event-applications")||"[]");applications.push({...data,eventSlug,businessCard:cardName,status:"대기",appliedAt:new Date().toISOString()});localStorage.setItem("noogu:event-applications",JSON.stringify(applications));setApplicant(String(data.name||""));setSent(true)};
  if(sent)return <div className="card empty"><div className="empty-icon" style={{background:"#effbd7"}}><CheckCircle2 size={23} color="#4d7310"/></div><h3>{applicant}님의 참가 신청이 접수되었습니다</h3><p>승인 결과와 체크인 QR을 입력하신 이메일로 안내해 드릴게요.</p><button className="button light" onClick={()=>setSent(false)}>추가 신청하기</button></div>;
  return <form className="card card-pad form-grid" onSubmit={submit}><h2 className="section-title">참가 신청</h2><div className="two-col"><label className="field"><span>이름 *</span><input className="input" name="name" required placeholder="김한재"/></label><label className="field"><span>회사명 *</span><input className="input" name="company" required placeholder="NOOGU"/></label></div><div className="two-col"><label className="field"><span>직급</span><input className="input" name="jobTitle" placeholder="Product Lead"/></label><label className="field"><span>전화번호</span><input className="input" name="phone" type="tel" placeholder="010-0000-0000"/></label></div><label className="field"><span>이메일 *</span><input className="input" name="email" type="email" required placeholder="name@company.com"/></label><label className="field"><span>관심 분야</span><input className="input" name="interests" placeholder="브랜드, 제조, 투자"/></label><label className="field"><span>소개</span><textarea className="textarea" name="introduction" placeholder="이 행사에서 만나고 싶은 사람이나 나누고 싶은 이야기를 알려주세요."/></label><input ref={fileRef} type="file" accept="image/png,image/jpeg" hidden onChange={event=>setCardName(event.target.files?.[0]?.name||"")}/><button type="button" className="button ghost full" onClick={()=>fileRef.current?.click()}><Upload size={16}/> {cardName||"명함 업로드 (선택)"}</button><button className="button green full" type="submit">승인 요청하기</button><p className="list-sub" style={{textAlign:"center"}}>승인제 행사입니다. 주최자 확인 후 이메일로 안내됩니다.</p></form>;
}
